# Generated by Django 4.1.5 on 2023-02-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_linkprofile_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_url',
        ),
    ]
