# Generated by Django 4.1.5 on 2023-02-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkprofile',
            old_name='display_name',
            new_name='profile_title',
        ),
    ]
