# Generated by Django 4.1.5 on 2023-02-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_display_name_linkprofile_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='linkprofile',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='linkprofile',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
