# Generated by Django 4.1.5 on 2023-02-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_linkstyle_shadows'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkprofile',
            name='radius',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
