# Generated by Django 4.1.5 on 2023-02-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_linkprofile_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkstyle',
            name='isSoftShadow',
            field=models.BooleanField(default=False),
        ),
    ]
