# Generated by Django 4.1.5 on 2023-02-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_linkstyle_issoftshadow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkprofile',
            name='color_hex',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
