# Generated by Django 4.1.5 on 2023-02-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_linkprofile_color_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.CharField(max_length=2550),
        ),
    ]
