# Generated by Django 4.1.5 on 2023-02-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_link_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='href',
            field=models.CharField(max_length=2550),
        ),
    ]
